server:
  port: 11000

# REDIS (RedisProperties)
# Redis数据库索引（默认为0）
spring.redis.database : 0
# Redis服务器地址
spring.redis.host : 172.0.0.1
# Redis服务器连接端口
spring.redis.port : 6379
# Redis服务器连接密码（默认为空）
spring.redis.password :
# 连接池最大连接数（使用负值表示没有限制）
spring.redis.pool.max-active : 8
# 连接池最大阻塞等待时间（使用负值表示没有限制）
spring.redis.pool.max-wait : -1
# 连接池中的最大空闲连接
spring.redis.pool.max-idle : 8
# 连接池中的最小空闲连接
spring.redis.pool.min-idle : 0
# 连接超时时间（毫秒）
spring.redis.timeout : 0

#freemarker
#freemarker后缀
spring.freemarker.suffix : .ftl
#freemarker解析路径
spring.freemarker.template-loader-path : classpath:/templates/
spring.freemarker.allow-request-override : false
#freemarker缓存设置
spring.freemarker.cache : false
spring.freemarker.check-template-location : true
spring.freemarker.charset : UTF-8
spring.freemarker.content-type : text/html
spring.freemarker.expose-request-attributes : true
spring.freemarker.request-context-attribute : request
spring.freemarker.expose-session-attributes : true
spring.freemarker.expose-spring-macro-helpers : false