package top.mrzhao.entity;

import org.springframework.stereotype.Component;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table meeting
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Component
public class Meeting {
    /**
     * Database Column Remarks:
     *   会议id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.meeting_id
     *
     * @mbg.generated
     */
    private Integer meetingId;

    /**
     * Database Column Remarks:
     *   会议名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.meeting_name
     *
     * @mbg.generated
     */
    private String meetingName;

    /**
     * Database Column Remarks:
     *   会议内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.meeting_content
     *
     * @mbg.generated
     */
    private String meetingContent;

    /**
     * Database Column Remarks:
     *   会议状态（1按时开始 -1取消会议）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.meeting_status
     *
     * @mbg.generated
     */
    private Integer meetingStatus;

    /**
     * Database Column Remarks:
     *   参会部门id(0 为全体部门）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.meeting_department_id
     *
     * @mbg.generated
     */
    private Integer meetingDepartmentId;

    /**
     * Database Column Remarks:
     *   会议时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.meeting_time
     *
     * @mbg.generated
     */
    private Date meetingTime;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.meeting_id
     *
     * @return the value of meeting.meeting_id
     *
     * @mbg.generated
     */
    public Integer getMeetingId() {
        return meetingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.meeting_id
     *
     * @param meetingId the value for meeting.meeting_id
     *
     * @mbg.generated
     */
    public void setMeetingId(Integer meetingId) {
        this.meetingId = meetingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.meeting_name
     *
     * @return the value of meeting.meeting_name
     *
     * @mbg.generated
     */
    public String getMeetingName() {
        return meetingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.meeting_name
     *
     * @param meetingName the value for meeting.meeting_name
     *
     * @mbg.generated
     */
    public void setMeetingName(String meetingName) {
        this.meetingName = meetingName == null ? null : meetingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.meeting_content
     *
     * @return the value of meeting.meeting_content
     *
     * @mbg.generated
     */
    public String getMeetingContent() {
        return meetingContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.meeting_content
     *
     * @param meetingContent the value for meeting.meeting_content
     *
     * @mbg.generated
     */
    public void setMeetingContent(String meetingContent) {
        this.meetingContent = meetingContent == null ? null : meetingContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.meeting_status
     *
     * @return the value of meeting.meeting_status
     *
     * @mbg.generated
     */
    public Integer getMeetingStatus() {
        return meetingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.meeting_status
     *
     * @param meetingStatus the value for meeting.meeting_status
     *
     * @mbg.generated
     */
    public void setMeetingStatus(Integer meetingStatus) {
        this.meetingStatus = meetingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.meeting_department_id
     *
     * @return the value of meeting.meeting_department_id
     *
     * @mbg.generated
     */
    public Integer getMeetingDepartmentId() {
        return meetingDepartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.meeting_department_id
     *
     * @param meetingDepartmentId the value for meeting.meeting_department_id
     *
     * @mbg.generated
     */
    public void setMeetingDepartmentId(Integer meetingDepartmentId) {
        this.meetingDepartmentId = meetingDepartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.meeting_time
     *
     * @return the value of meeting.meeting_time
     *
     * @mbg.generated
     */
    public Date getMeetingTime() {
        return meetingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.meeting_time
     *
     * @param meetingTime the value for meeting.meeting_time
     *
     * @mbg.generated
     */
    public void setMeetingTime(Date meetingTime) {
        this.meetingTime = meetingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.create_time
     *
     * @return the value of meeting.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.create_time
     *
     * @param createTime the value for meeting.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.modify_time
     *
     * @return the value of meeting.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.modify_time
     *
     * @param modifyTime the value for meeting.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}