package top.mrzhao.entity;

import org.springframework.stereotype.Component;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table task
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Component
public class Task {
    /**
     * Database Column Remarks:
     *   任务id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_id
     *
     * @mbg.generated
     */
    private Integer taskId;

    /**
     * Database Column Remarks:
     *   任务名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_name
     *
     * @mbg.generated
     */
    private String taskName;

    /**
     * Database Column Remarks:
     *   任务所属部门id(0为所有部门）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_department_id
     *
     * @mbg.generated
     */
    private Integer taskDepartmentId;

    /**
     * Database Column Remarks:
     *   负责人id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_charge_id
     *
     * @mbg.generated
     */
    private Integer taskChargeId;

    /**
     * Database Column Remarks:
     *   任务内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_content
     *
     * @mbg.generated
     */
    private String taskContent;

    /**
     * Database Column Remarks:
     *   任务状态（1正在生效，0已停止，-1已废除）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_status
     *
     * @mbg.generated
     */
    private Byte taskStatus;

    /**
     * Database Column Remarks:
     *   任务周期（单位/小时）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_cycle
     *
     * @mbg.generated
     */
    private Integer taskCycle;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_id
     *
     * @return the value of task.task_id
     *
     * @mbg.generated
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_id
     *
     * @param taskId the value for task.task_id
     *
     * @mbg.generated
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_name
     *
     * @return the value of task.task_name
     *
     * @mbg.generated
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_name
     *
     * @param taskName the value for task.task_name
     *
     * @mbg.generated
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_department_id
     *
     * @return the value of task.task_department_id
     *
     * @mbg.generated
     */
    public Integer getTaskDepartmentId() {
        return taskDepartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_department_id
     *
     * @param taskDepartmentId the value for task.task_department_id
     *
     * @mbg.generated
     */
    public void setTaskDepartmentId(Integer taskDepartmentId) {
        this.taskDepartmentId = taskDepartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_charge_id
     *
     * @return the value of task.task_charge_id
     *
     * @mbg.generated
     */
    public Integer getTaskChargeId() {
        return taskChargeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_charge_id
     *
     * @param taskChargeId the value for task.task_charge_id
     *
     * @mbg.generated
     */
    public void setTaskChargeId(Integer taskChargeId) {
        this.taskChargeId = taskChargeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_content
     *
     * @return the value of task.task_content
     *
     * @mbg.generated
     */
    public String getTaskContent() {
        return taskContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_content
     *
     * @param taskContent the value for task.task_content
     *
     * @mbg.generated
     */
    public void setTaskContent(String taskContent) {
        this.taskContent = taskContent == null ? null : taskContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_status
     *
     * @return the value of task.task_status
     *
     * @mbg.generated
     */
    public Byte getTaskStatus() {
        return taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_status
     *
     * @param taskStatus the value for task.task_status
     *
     * @mbg.generated
     */
    public void setTaskStatus(Byte taskStatus) {
        this.taskStatus = taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_cycle
     *
     * @return the value of task.task_cycle
     *
     * @mbg.generated
     */
    public Integer getTaskCycle() {
        return taskCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_cycle
     *
     * @param taskCycle the value for task.task_cycle
     *
     * @mbg.generated
     */
    public void setTaskCycle(Integer taskCycle) {
        this.taskCycle = taskCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.create_time
     *
     * @return the value of task.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.create_time
     *
     * @param createTime the value for task.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.modify_time
     *
     * @return the value of task.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.modify_time
     *
     * @param modifyTime the value for task.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}