package top.mrzhao.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_task
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class UserTask {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_task.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_task.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   任务id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_task.task_id
     *
     * @mbg.generated
     */
    private Integer taskId;

    /**
     * Database Column Remarks:
     *   任务完成状态（1进行中 2已递交 3已完成）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_task.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   对管理员的留言
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_task.message_waiting
     *
     * @mbg.generated
     */
    private String messageWaiting;

    /**
     * Database Column Remarks:
     *   开始任务时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_task.start_time
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     * Database Column Remarks:
     *   应完成的最后时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_task.dead_line
     *
     * @mbg.generated
     */
    private Date deadLine;

    /**
     * Database Column Remarks:
     *   递交时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_task.commit_time
     *
     * @mbg.generated
     */
    private Date commitTime;

    /**
     * Database Column Remarks:
     *   完成时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_task.end_time
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_task.id
     *
     * @return the value of user_task.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_task.id
     *
     * @param id the value for user_task.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_task.user_id
     *
     * @return the value of user_task.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_task.user_id
     *
     * @param userId the value for user_task.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_task.task_id
     *
     * @return the value of user_task.task_id
     *
     * @mbg.generated
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_task.task_id
     *
     * @param taskId the value for user_task.task_id
     *
     * @mbg.generated
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_task.status
     *
     * @return the value of user_task.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_task.status
     *
     * @param status the value for user_task.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_task.message_waiting
     *
     * @return the value of user_task.message_waiting
     *
     * @mbg.generated
     */
    public String getMessageWaiting() {
        return messageWaiting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_task.message_waiting
     *
     * @param messageWaiting the value for user_task.message_waiting
     *
     * @mbg.generated
     */
    public void setMessageWaiting(String messageWaiting) {
        this.messageWaiting = messageWaiting == null ? null : messageWaiting.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_task.start_time
     *
     * @return the value of user_task.start_time
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_task.start_time
     *
     * @param startTime the value for user_task.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_task.dead_line
     *
     * @return the value of user_task.dead_line
     *
     * @mbg.generated
     */
    public Date getDeadLine() {
        return deadLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_task.dead_line
     *
     * @param deadLine the value for user_task.dead_line
     *
     * @mbg.generated
     */
    public void setDeadLine(Date deadLine) {
        this.deadLine = deadLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_task.commit_time
     *
     * @return the value of user_task.commit_time
     *
     * @mbg.generated
     */
    public Date getCommitTime() {
        return commitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_task.commit_time
     *
     * @param commitTime the value for user_task.commit_time
     *
     * @mbg.generated
     */
    public void setCommitTime(Date commitTime) {
        this.commitTime = commitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_task.end_time
     *
     * @return the value of user_task.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_task.end_time
     *
     * @param endTime the value for user_task.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}