package top.mrzhao.entity;

import org.springframework.stereotype.Component;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_meeting
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Component
public class UserMeeting {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_meeting.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_meeting.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   会议id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_meeting.meeting_id
     *
     * @mbg.generated
     */
    private Integer meetingId;

    /**
     * Database Column Remarks:
     *   查看状态(0未查看 1已查看 -1已作废)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_meeting.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_meeting.id
     *
     * @return the value of user_meeting.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_meeting.id
     *
     * @param id the value for user_meeting.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_meeting.user_id
     *
     * @return the value of user_meeting.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_meeting.user_id
     *
     * @param userId the value for user_meeting.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_meeting.meeting_id
     *
     * @return the value of user_meeting.meeting_id
     *
     * @mbg.generated
     */
    public Integer getMeetingId() {
        return meetingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_meeting.meeting_id
     *
     * @param meetingId the value for user_meeting.meeting_id
     *
     * @mbg.generated
     */
    public void setMeetingId(Integer meetingId) {
        this.meetingId = meetingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_meeting.status
     *
     * @return the value of user_meeting.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_meeting.status
     *
     * @param status the value for user_meeting.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}