package top.mrzhao.dao;

import org.apache.ibatis.annotations.Param;
import top.mrzhao.entity.UserTask;
import top.mrzhao.entity.UserTaskExample;

import java.util.List;

public interface UserTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_task
     *
     * @mbg.generated
     */
    long countByExample(UserTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_task
     *
     * @mbg.generated
     */
    int deleteByExample(UserTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_task
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_task
     *
     * @mbg.generated
     */
    int insert(UserTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_task
     *
     * @mbg.generated
     */
    int insertSelective(UserTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_task
     *
     * @mbg.generated
     */
    List<UserTask> selectByExample(UserTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_task
     *
     * @mbg.generated
     */
    UserTask selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_task
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserTask record, @Param("example") UserTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_task
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserTask record, @Param("example") UserTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserTask record);
}