package top.mrzhao.dao;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import top.mrzhao.entity.UserMeeting;
import top.mrzhao.entity.UserMeetingExample;

import java.util.List;
@Component
public interface UserMeetingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_meeting
     *
     * @mbg.generated
     */
    long countByExample(UserMeetingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_meeting
     *
     * @mbg.generated
     */
    int deleteByExample(UserMeetingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_meeting
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_meeting
     *
     * @mbg.generated
     */
    int insert(UserMeeting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_meeting
     *
     * @mbg.generated
     */
    int insertSelective(UserMeeting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_meeting
     *
     * @mbg.generated
     */
    List<UserMeeting> selectByExample(UserMeetingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_meeting
     *
     * @mbg.generated
     */
    UserMeeting selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_meeting
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserMeeting record, @Param("example") UserMeetingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_meeting
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserMeeting record, @Param("example") UserMeetingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_meeting
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserMeeting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_meeting
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserMeeting record);
}